### ISSUE TITLE
Unknown or bad timezone (UTC-8) in timezones/plugin.php

### ISSUE THREAD

**Issue by s22-tech** [YOURLS/timezones#10]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.1

### Description

Choosing UTC -8 in the pull down menu caused an error:

```
Fatal error: Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone (UTC-8) in /home/xxxx/yourls/plugins/timezones/plugin.php:81 
Stack trace: 
#0 /home/xxxx/yourls/user/plugins/timezones/plugin.php(81): DateTimeZone->__construct('UTC-8') 
#1 /home/xxxx/yourls/user/plugins/timezones/plugin.php(95): yourls_tzp_timezoned_offset('UTC-8') 
#2 /home/xxxx/yourls/user/plugins/timezones/admin.php(46): yourls_tzp_timezoned_timestamp(1642550402, 'UTC-8') 
#3 /home/xxxx/yourls/includes/functions-plugins.php(775): yourls_tzp_admin_page() 
#4 /home/xxxx/yourls/admin/plugins.php(8): yourls_plugin_admin_page('time_zone_confi...') 
#5 {main} thrown in /home/xxxx/yourls/user/plugins/timezones/plugin.php on line 81
```

### Reproduction steps

I simply chose UTC -8 in the pull down menu instead of a city name.

**Comment by s22-tech** [comment]
I deactivated the plugin, deleted the timezone options in the db, reactivated the plugin, and experienced the same problem.

After de/activating again, I selected "America/Los_Angeles" and it took.  However the UTC time is the current time in L.A. and the L.A. time is 9 hours behind.

I pulled both yourls_tzp_timezoned_*** functions and tested them in an external PHP file and they returned the proper time, so something else must be changing the timestamp/timezone.

**Comment by s22-tech** [comment]
After more testing, I ended up with another Uncaught Exception error, except this time the offset was NULL.  Not sure what happened to cause it.  The timezone options in the db are still intact so there shouldn't be an error.

Calling it quits for the day.  Will wait to hear what you have to say.

**Comment by ozh** [comment]
Indeed, the plugin code is incorrect when UTC + an offset is picked, this should be fixed.

Question, though : why would someone pick UTC + an offset instead of the biggest city nearby ? I'm tempted to just delete the whole UTC option group to be honest ...

**Comment by s22-tech** [comment]
I don't use the numbered offsets.  I was just testing and thought I'd let you know.

**Comment by ozh** [comment]
Thanks for reporting :)

This is now fixed and picking an UTC time works as expected.
