### ISSUE TITLE
Errors when trying to change timezone

### ISSUE THREAD

**Issue by SophiaAtkinson** [YOURLS/timezones#12]
### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.19.1

### Description

When attempting to change the timezone the following error is shown
Note that I'm using PHP 8.0.14
`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'option_id' doesn't have a default value in \includes\vendor\aura\sql\src\AbstractExtendedPdo.php:565 Stack trace: #0 \includes\vendor\aura\sql\src\AbstractExtendedPdo.php(565): PDOStatement->execute() #1 \includes\vendor\aura\sql\src\AbstractExtendedPdo.php(237): Aura\Sql\AbstractExtendedPdo->perform('INSERT INTO you...', Array) #2 \includes\Database\Options.php(211): Aura\Sql\AbstractExtendedPdo->fetchAffected('INSERT INTO you...', Array) #3 \includes\Database\Options.php(159): YOURLS\Database\Options->add('timezone', Array) #4 \includes\functions-options.php(71): YOURLS\Database\Options->update('timezone', Array) #5 \user\plugins\timezones\admin.php(270): yourls_update_option('timezone', Array) #6 \user\plugins\timezones\admin.php(15): yourls_tzp_config_update_settings() #7 \includes\functions-plugins.php(815): yourls_tzp_admin_page() #8 \admin\plugins.php(8): yourls_plugin_admin_page('time_zone_confi...') #9 {main} thrown in \includes\vendor\aura\sql\src\AbstractExtendedPdo.php on line 565`

### Reproduction steps

1. Install plugin
2. Activate plugin
3. try and change timezone

**Comment by ozh** [comment]
Cannot reproduce. Works fine for me using latest plugin version (1.3), on YOURLS 1.9.1, with PHP 8.1.5

**Comment by SophiaAtkinson** [comment]
It seems it was purely a bug with my DB, it's all working now, sorry for the inconvenience.
